### ISSUE TITLE
Errors should be decoupled from the backing storage

### ISSUE THREAD

**Issue by sirioz** [StorageKit/StorageKit#18]
Hi,

I think that error handling should be decoupled from the backing storage.
Now if I want to catch errors I need to reintroduce a dependancy to a Realm or CoreData.

Example:

```
do {
            try storage.mainContext?.add(user)
        } catch (let error) // this error depends on the backing storage module

```

**Comment by MarcoSantarossa** [comment]
Hi @sirioz,
You're perfectly right. In our `TODO` backlog, we have the task to add a common interface for the errors of both Realm and CoreData. At the moment, we are catching several errors internally but we don't expose because we have to define a common and clean interface to use for any kind of storage we are going to support. We didn't start to work on it yet and I'm not able to provide a date for this feature. Since you have shown us that it has a quite high priority, we are going to prioritize it and start working on it asap.

We can leave this issue open to keep track since I guess other people are interesting on it.

**Comment by MarcoSantarossa** [comment]
Issues fixed with https://github.com/StorageKit/StorageKit/pull/23. Thank you @sirioz  for being our main contributor 😄
